# Generated by Django 5.1.2 on 2024-11-20 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_q_id', models.PositiveIntegerField(default=1, verbose_name='current_q_id')),
                ('current_h_id', models.TextField(default='0', verbose_name='current_h_id')),
                ('kc_progress', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('h_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('img_name', models.TextField(default='', verbose_name='img_name')),
                ('kc_id', models.TextField(default='', verbose_name='kc_id')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeComponent',
            fields=[
                ('kc_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('o_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(default='', verbose_name='feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sectionname', models.TextField(blank=True, max_length=500)),
                ('numberofquestions', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.PositiveIntegerField(default=1, verbose_name='q_id')),
                ('selected_opt_idx', models.PositiveIntegerField(default=1, verbose_name='selected_opt_idx')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is_correct')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('img_url', models.TextField(default='', verbose_name='img_url')),
                ('q_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('img_name', models.TextField(default='', verbose_name='img_name')),
                ('total_hints', models.PositiveIntegerField(default=0, verbose_name='total_hints')),
                ('example_problem', models.TextField(default='', verbose_name='example_problem')),
                ('kcs', models.ManyToManyField(to='storyboard.knowledgecomponent')),
            ],
        ),
    ]
