# Generated by Django 5.1.2 on 2024-11-07 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('h_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('img_name', models.TextField(default='', verbose_name='img_name')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeComponent',
            fields=[
                ('kc_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('o_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(default='', verbose_name='feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('img_url', models.TextField(default='', verbose_name='img_url')),
                ('q_id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='', verbose_name='text')),
                ('img_name', models.TextField(default='', verbose_name='img_name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sectionname', models.TextField(blank=True, max_length=500)),
                ('numberofquestions', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
